apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "366f513"
        buildate: "2023-08-08T22:55:19"
    spec:
      containers:
        - name: products
          image: host.k3d.internal:5000/products:latest
          ports:
            - containerPort: 8080
              name: 8080-tcp
